[project]
name = "sundown"
version = "0.1.0"
description = "Interface with DeviantArt's Eclipse browser API."
authors = [
    {name = "Nemris", email = "nemris@protonmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp (>=3.11.18,<4.0.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)"
]

[tool.poetry.group.dev.dependencies]
hypothesis = "^6.131.14"
black = "^25.1.0"
pylint = "^4.0.4"
pytest = "^9.0.2"
pytest-asyncio = "^1.3.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
asyncio_default_test_loop_scope = "function"
